################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/PeripheralPins.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/analogin_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/analogin_device.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/analogout_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/analogout_device.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/can_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/flash_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/gpio_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/gpio_irq_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/gpio_irq_device.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/hal_tick_overrides.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/i2c_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/l4_retarget.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/lp_ticker.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_board.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_crc_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_overrides.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_retarget.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_sdk_boot.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/mbed_tz_context.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/pinmap.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/port_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/pwmout_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/pwmout_device.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/qspi_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/rtc_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/serial_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/serial_device.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/sleep.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/spi_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/startup_stm32l432xx.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_adc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_adc_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_can.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_can_legacy.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_comp.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_cortex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_crc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_crc_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_cryp.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_cryp_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dac.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dac_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dcmi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dfsdm.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dfsdm_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dma.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dma2d.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dma_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_dsi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_firewall.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_flash.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_flash_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_flash_ramfunc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_gfxmmu.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_gpio.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_hash.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_hash_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_hcd.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_i2c.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_i2c_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_irda.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_iwdg.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_lcd.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_lptim.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_ltdc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_ltdc_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_nand.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_nor.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_opamp.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_opamp_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_ospi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_pcd.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_pcd_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_pwr.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_pwr_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_qspi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_rcc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_rcc_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_rng.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_rtc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_rtc_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_sai.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_sai_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_sd.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_sd_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_smartcard.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_smartcard_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_smbus.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_spi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_spi_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_sram.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_swpmi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_tim.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_tim_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_tsc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_uart.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_uart_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_usart.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_usart_ex.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_hal_wwdg.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_adc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_comp.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_crc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_crs.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_dac.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_dma.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_dma2d.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_exti.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_fmc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_gpio.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_i2c.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_lptim.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_lpuart.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_opamp.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_pwr.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_rcc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_rng.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_rtc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_sdmmc.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_spi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_swpmi.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_tim.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_usart.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_usb.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm32l4xx_ll_utils.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/stm_spi_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/system_clock.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/system_stm32l4xx.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/trng_api.o \
../mbed/TARGET_NUCLEO_L432KC/TOOLCHAIN_GCC_ARM/us_ticker.o 


# Each subdirectory must supply rules for building sources it contributes

